Vagrant.configure("2") do |config|

  if Vagrant.has_plugin? "vagrant-vbguest"
     config.vbguest.no_install = true
     config.vbguest.auto_update = false
     config.vbguest.no_remote = true
  end
  config.vm.define :servidor do |servidor|
    servidor.vm.box = "bento/centos-7.9"
    servidor.vm.network :private_network, ip: "192.168.50.4"
    servidor.vm.hostname = "servidor"
    servidor.vm.provider "virtualbox" do |v|
      v.cpus = 2 
    end
  end
end